### ISSUE TITLE
Can not run example

### ISSUE THREAD

**Issue by kenny-lee-1992** [nok/onedollar-unistroke-coffee#1]
Dear,

Can you guide me how to run your example ? I have download the source code and browse example/jquery but it not work !

Thanks and Best Regards,

**Comment by nok** [comment]
Hello @minhlong,

this example doesn't have any visual feedback of your interaction. But the results are shown in the [console of your browser](https://developers.google.com/web/tools/chrome-devtools/console/):

![screen shot 2016-11-30 at 01 32 18](https://cloud.githubusercontent.com/assets/670641/20734917/dcae3c5c-b69c-11e6-9a14-0a529989accc.png)

It's pretty straightforward to avoid unnecessary additional code. But you're right that I should create a more useable example to demonstrate the benefit of the library.

Thanks,
Darius

**Comment by kenny-lee-1992** [comment]
hi Nok,

Thank you so much for your reply :)

Best Regards
